# Generated by Django 3.1.7 on 2021-04-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youTube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videos',
            new_name='title',
        ),
    ]
